### ISSUE TITLE
Files not syncing, though get.log looks normal Kobo Forma

### ISSUE THREAD

**Issue by profeshish** [fsantini/KoboCloud#154]
I'm on the latest kobo update, which I believe was this month. Files are not currently syncing for me though kobocloud install looks normal and I have uninstalled and redone the steps multiple times.

typing out get.log to avoid showing my file locations:
(begin, not part of it just putting so everyone knows where it starts)
2023-06-23_15:29:05 waiting for internet connection
Reading # (comment stuff)
Comment found
(this repeats a few times for all the comments)
Reading (my cloud url)
Getting (my cloud url)
shareID: (last part of my cloud url)
davServer: (domain of my cloud url)
davServerWithOwncloudPath: (domain of my cloud url)
2023-06-23_15:31:18 done
(end, again not included)

the only non-commented line in my kobocloudrc is my cloud share url, which I've tested in browser and confirmed displays my files, I have an epub directly in that folder too. I'm on a normal signed in Kobo Forma and not like a hacked Kobo in case that makes a difference.

**Comment by profeshish** [comment]
sorry I didn't know how the markups work here, fixing it.

**Comment by profeshish** [comment]
Fixed it with parenthesis instead of greater than less than brackets.

**Comment by groentebroer** [comment]
Previously there were some issues with empty lines after the cloud URL.
Please add a return after the cloud url, see if that helps.

**Comment by groentebroer** [comment]
Please also check the following settings, if webdav is enabled on your OwnCloud.
If still not working, please provide the URL, so we can test.

from the readme:
```
Important: Webdav for public folders should be enabled, see: https://docs.nextcloud.com/server/20/user_manual/en/files/access_webdav.html#accessing-public-shares-over-webdav for more info.
```

**Comment by groentebroer** [comment]
Hi @profeshish 
It seems that pCloud now has a new format for sharing, so if you were using that, that could cause the problems you had above. This is new sharing is now build in. Please be aware that this method does **NOT** include subfolders, so only files in the root of the publicly shared folder will work.

**Comment by profeshish** [comment]
I'm using nextcloud, WebDAV is enabled and confirmed working since I use the same server for my caldav sync. I also verified the kobocloudrc, still the same results.

**Comment by groentebroer** [comment]
If still not working, please provide the URL, so we can test.
Can you also let us know which device and firmware version?

**Comment by profeshish** [comment]
Kobo Forma on 4.37.21533 (6/21/23)

Not really comfortable sharing my personal nextcloud info, if there's a test server you want me to use let me know.

**Comment by profeshish** [comment]
It was Ulysses right? I think it grabbed that correctly I'll go ahead and close it out

**Comment by groentebroer** [comment]
Yes, if you want us to investigate further, we need a (demo) url to verify.
